/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = ['configEncrypted', 'createdAt', 'id', 'name', 'status', 'type', 'updatedAt', 'userId'] as const
  $columns = AccountSchema.$columns
  @column()
  declare configEncrypted: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare status: string
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AiSettingSchema extends BaseModel {
  static $columns = ['aiSource', 'createdAt', 'customSpamGuidelines', 'customizeSpamGuidelines', 'enableVectorDb', 'id', 'ollamaBaseUrl', 'openRouterApiKey', 'selectedEmbedModel', 'selectedModel', 'temperature', 'topP', 'updatedAt', 'userId'] as const
  $columns = AiSettingSchema.$columns
  @column()
  declare aiSource: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customSpamGuidelines: string
  @column()
  declare customizeSpamGuidelines: boolean
  @column()
  declare enableVectorDb: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ollamaBaseUrl: string
  @column()
  declare openRouterApiKey: string
  @column()
  declare selectedEmbedModel: string
  @column()
  declare selectedModel: string
  @column()
  declare temperature: number
  @column()
  declare topP: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AlertSchema extends BaseModel {
  static $columns = ['context', 'createdAt', 'goto', 'id', 'message', 'type', 'updatedAt', 'user', 'userId'] as const
  $columns = AlertSchema.$columns
  @column()
  declare context: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare goto: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare user: string
  @column()
  declare userId: number
}

export class AnalyzedEmailSchema extends BaseModel {
  static $columns = ['accountId', 'aiProvider', 'analyzedAt', 'body', 'cost', 'createdAt', 'emailId', 'id', 'isSpam', 'reasoning', 'score', 'sender', 'subject', 'updatedAt', 'userId', 'userValidated'] as const
  $columns = AnalyzedEmailSchema.$columns
  @column()
  declare accountId: string
  @column()
  declare aiProvider: string
  @column.dateTime()
  declare analyzedAt: DateTime | null
  @column()
  declare body: string
  @column()
  declare cost: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare emailId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSpam: boolean
  @column()
  declare reasoning: string
  @column()
  declare score: number
  @column()
  declare sender: string
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare userValidated: number | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CommunityTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'token', 'updatedAt', 'userId'] as const
  $columns = CommunityTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class EmailChecksumSchema extends BaseModel {
  static $columns = ['checksum', 'createdAt', 'id', 'updatedAt', 'userId'] as const
  $columns = EmailChecksumSchema.$columns
  @column()
  declare checksum: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class GeneralSettingSchema extends BaseModel {
  static $columns = ['aiSensitivity', 'createdAt', 'cronExpression', 'customDateFormat', 'dateFormat', 'emailAgeDays', 'enableCron', 'id', 'schedulerMode', 'schedulerSimpleUnit', 'schedulerSimpleValue', 'simplifyEmailContent', 'simplifyEmailContentMode', 'timeFormat', 'updatedAt', 'userId'] as const
  $columns = GeneralSettingSchema.$columns
  @column()
  declare aiSensitivity: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string
  @column()
  declare customDateFormat: string
  @column()
  declare dateFormat: string
  @column()
  declare emailAgeDays: number
  @column()
  declare enableCron: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare schedulerMode: string
  @column()
  declare schedulerSimpleUnit: string
  @column()
  declare schedulerSimpleValue: number
  @column()
  declare simplifyEmailContent: boolean
  @column()
  declare simplifyEmailContentMode: string
  @column()
  declare timeFormat: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RuleSchema extends BaseModel {
  static $columns = ['createdAt', 'emailAccounts', 'enabled', 'id', 'name', 'text', 'updatedAt', 'userId'] as const
  $columns = RuleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare emailAccounts: string | null
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare text: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
