/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Accounts: () => import('#controllers/accounts_controller'),
  Alerts: () => import('#controllers/alerts_controller'),
  AnalyzedEmails: () => import('#controllers/analyzed_emails_controller'),
  Community: () => import('#controllers/community_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Oauth: () => import('#controllers/oauth_controller'),
  Process: () => import('#controllers/process_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Rules: () => import('#controllers/rules_controller'),
  Settings: () => import('#controllers/settings_controller'),
  VectorDb: () => import('#controllers/vector_db_controller'),
}
